# docker-composeのバージョンを指定
version: "3.9"

# db(MySQL),app(Flask)のコンテナを作成
services:
  nginx:
    # コンテナ名をNginxに設定
    container_name:
      web_con
      # ビルドコンテキストはカレントディレクトリ
    # nginxのDockerfileをビルドする
    build:
      context: .
      dockerfile: Docker/nginx/Dockerfile
      # ローカルの5000番ポートとコンテナの80番ポートをつなぐ
      # ボリュームを指定
      # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  app:
    # コンテナ名をFlaskに設定
    container_name: Flask
    # FlaskのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Flask/Dockerfile
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    volumes:
      - ./ChatApp:/code/
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
